"""
Data contracts across trust boundaries.
Plane transitions occur strictly via validated schemas, never raw text.
"""
from __future__ import annotations
from enum import Enum
from datetime import datetime, timezone
import uuid
import re

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator


# ─────────────────────────────────────────────────────────────────────────────
# Provenance tracking
# Origin markers used by the controller to separate untrusted text signals
# from authoritative market data.
# ─────────────────────────────────────────────────────────────────────────────
class Provenance(str, Enum):
    UNTRUSTED_TEXT = "untrusted_text"  # Extracted by Perception LLM from raw feeds
    MARKET_DATA = "market_data"        # Direct from Alpaca API via trusted runtime
    DETERMINISTIC = "deterministic"    # Calculated locally by trusted logic


# ─────────────────────────────────────────────────────────────────────────────
# Plane 1 -> 2: PerceptionOutput
# Constrained output schema for the untrusted reading model (0 tools attached).
# ─────────────────────────────────────────────────────────────────────────────
class Sentiment(str, Enum):
    BULLISH = "bullish"
    BEARISH = "bearish"
    NEUTRAL = "neutral"


class ClaimType(str, Enum):
    PRICE_TARGET = "price_target"
    PCT_MOVE = "pct_move"
    EARNINGS = "earnings"
    RATING_CHANGE = "rating_change"
    EVENT = "event"
    OTHER = "other"


class ExtractedClaim(BaseModel):
    model_config = ConfigDict(extra="forbid")
    text: str = Field(max_length=500)
    claim_type: ClaimType
    numeric_value: float | None = None
    numeric_unit: str | None = Field(default=None, max_length=20)  # e.g. "USD", "%", "shares"


class PerceptionOutput(BaseModel):
    model_config = ConfigDict(extra="forbid")  # Prevent schema leakage during decoding

    symbols: list[str] = Field(default_factory=list, max_length=10)
    sentiment: Sentiment
    extracted_claims: list[ExtractedClaim] = Field(default_factory=list, max_length=20)
    entities: list[str] = Field(default_factory=list, max_length=20)
    source_ref: str = Field(max_length=200)

    @field_validator("symbols")
    @classmethod
    def symbols_uppercase_ascii(cls, v: list[str]) -> list[str]:
        # Drop homoglyphs and unicode lookalikes; enforce standard US ticker format.
        # Dedupe while preserving first-seen order.
        seen: set[str] = set()
        clean: list[str] = []
        for s in v:
            s2 = s.strip().upper()
            if not re.fullmatch(r"[A-Z]{1,5}", s2):
                raise ValueError(f"symbol failed ASCII/homoglyph check: {s!r}")
            if s2 not in seen:
                seen.add(s2)
                clean.append(s2)
        return clean


# ─────────────────────────────────────────────────────────────────────────────
# Plane 2 -> 3: AirlockedPerception
# Normalized and tagged payload passed from the AIRLOCK gateway to the controller.
# ─────────────────────────────────────────────────────────────────────────────
class AirlockedPerception(BaseModel):
    model_config = ConfigDict(extra="forbid")
    payload: PerceptionOutput
    provenance: Provenance = Provenance.UNTRUSTED_TEXT
    airlock_id: str = Field(default_factory=lambda: uuid.uuid4().hex)
    ingested_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    anomalies: list[str] = Field(default_factory=list)  # Non-fatal sanitization flags


# ─────────────────────────────────────────────────────────────────────────────
# Plane 3: TradeIntent
# Proposed action generated by strategy logic before pre-trade risk evaluation.
# ─────────────────────────────────────────────────────────────────────────────
class Side(str, Enum):
    BUY = "buy"
    SELL = "sell"


class OrderType(str, Enum):
    MARKET = "market"
    LIMIT = "limit"


class TradeIntent(BaseModel):
    model_config = ConfigDict(extra="forbid")

    symbol: str = Field(pattern=r"^[A-Z]{1,5}$")
    side: Side
    qty: int = Field(gt=0, le=10_000)          # NEW — source of truth for order sizing
    notional: float = Field(gt=0, le=1_000_000)  # informational: qty * price at decision time
    order_type: OrderType = OrderType.MARKET
    limit_price: float | None = Field(default=None, gt=0)
    stop_loss_price: float = Field(gt=0)
    thesis_ref: str

    @model_validator(mode="after")
    def limit_price_matches_type(self) -> "TradeIntent":
        if self.order_type == OrderType.LIMIT and self.limit_price is None:
            raise ValueError("limit order requires limit_price")
        if self.order_type == OrderType.MARKET and self.limit_price is not None:
            raise ValueError("market order must not carry limit_price")
        return self

    # Note: directional stop validation (e.g. stop < entry for buys) requires
    # live market quotes and is evaluated inside the Execution Controller.


# ─────────────────────────────────────────────────────────────────────────────
# Plane 3 Output: ControllerVerdict
# Deterministic validation result from the risk engine.
# ─────────────────────────────────────────────────────────────────────────────
class Severity(str, Enum):
    INFO = "info"
    WARN = "warn"
    BLOCK = "block"


class CheckResult(BaseModel):
    model_config = ConfigDict(extra="forbid")
    name: str
    passed: bool
    severity: Severity
    detail: str = Field(max_length=300)


class Decision(str, Enum):
    PASS = "PASS"
    VETO = "VETO"


class ControllerVerdict(BaseModel):
    model_config = ConfigDict(extra="forbid")

    decision_id: str = Field(default_factory=lambda: uuid.uuid4().hex)
    intent: TradeIntent | None  # None if rejected prior to intent parsing
    checks: list[CheckResult]
    final: Decision
    approved_notional: float = Field(ge=0)
    reason: str = Field(max_length=500)
    evaluated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    @model_validator(mode="after")
    def veto_is_contagious(self) -> "ControllerVerdict":
        """Any failed BLOCK-level check forces final=VETO and zeroes sizing.
        This is the executable form of the product's core promise; it is an
        integrity assert on verdict construction, not the decision itself.
        The controller is responsible for failing closed if this raises."""
        has_block = any((not c.passed) and c.severity == Severity.BLOCK for c in self.checks)
        if has_block and self.final != Decision.VETO:
            raise ValueError("Invariant violation: failed BLOCK check requires final=VETO")
        if self.final == Decision.VETO and self.approved_notional != 0:
            raise ValueError("Invariant violation: VETO requires approved_notional=0")
        return self